# Generated by Django 3.2.8 on 2021-10-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211007_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='doc_identificacao',
        ),
    ]
