# Generated by Django 3.2.8 on 2021-10-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0004_auto_20211007_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='doc_identificacao',
        ),
        migrations.DeleteModel(
            name='DocIdentificacao',
        ),
    ]
